/**
 * Render the work grid in index.html from projects.json.
 *
 * projects.json is the single source of truth. Array order is grid order; to
 * rearrange the grid, reorder the entries there and re-run this script. Nothing
 * in the card markup should ever be hand-edited — everything between the
 * PROJECTS:START and PROJECTS:END markers in index.html is regenerated.
 *
 * Projects with "published": false stay in the data file but are excluded from
 * the grid, from the stagger and from the next-project loop, so a withheld
 * project comes back by flipping one boolean.
 *
 *   node make_projects.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const DATA = join(ROOT, "projects.json");
const PAGE = join(ROOT, "index.html");

const START =
  "<!-- PROJECTS:START — generated by make_projects.mjs, do not edit by hand -->";
const END = "<!-- PROJECTS:END -->";
const I = " ".repeat(8);

const die = (msg) => {
  console.error(msg);
  process.exit(1);
};

const esc = (s) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

function load() {
  const data = JSON.parse(readFileSync(DATA, "utf8"));
  const { studios } = data;
  const published = data.projects.filter((p) => p.published);
  if (!published.length)
    die("projects.json: no published projects — refusing to empty the grid.");
  for (const p of published)
    if (!studios[p.studio]) die(`${p.slug}: unknown studio "${p.studio}"`);
  return { studios, published, all: data.projects };
}

/**
 * One <a class="card"> per published project, in array order.
 *
 * data-delay reproduces the hand-authored 0/60/120 stagger, cycling within each
 * studio run so a filtered view still animates in properly.
 * data-next carries the next-project loop; it wraps at the end.
 */
function render(studios, projects) {
  const out = [I + START];
  let seen = null;
  let run = 0;

  projects.forEach((p, i) => {
    if (p.studio !== seen) {
      seen = p.studio;
      run = 0;
      out.push("", `${I}<!-- ${studios[p.studio]} -->`);
    }

    const next = projects[(i + 1) % projects.length].slug;
    const alt = `${p.name} — ${p.discipline.toLowerCase()}`;

    out.push(
      `${I}<a class="card reveal" href="#" data-studio="${p.studio}"` +
        ` data-category="${esc(p.category)}"` +
        ` data-slug="${p.slug}" data-next="${next}" data-delay="${(run % 3) * 60}">`,
      `${I}  <div class="card__frame">`,
      `${I}    <img src="${p.thumb}" alt="${esc(alt)}" loading="lazy" decoding="async">`,
      `${I}    <span class="card__studio">${studios[p.studio]}</span>`,
      `${I}  </div>`,
      `${I}  <div class="card__body"><span class="card__name">${esc(p.name)}</span>` +
        `<span class="card__year">${p.year}</span></div>`,
      `${I}  <p class="card__disc">${esc(p.discipline)}</p>`,
      `${I}</a>`,
      ""
    );
    run += 1;
  });

  if (out.at(-1) === "") out.pop();
  out.push(I + END);
  return out.join("\n");
}

const { studios, published, all } = load();
let page = readFileSync(PAGE, "utf8");

if (!page.includes(START) || !page.includes(END))
  die(
    `index.html is missing the PROJECTS markers. Expected:\n  ${START}\n  ...cards...\n  ${END}`
  );

const block = render(studios, published);
const from = page.indexOf(START);
const to = page.indexOf(END) + END.length;
page = page.slice(0, from) + block.trimStart() + page.slice(to);
writeFileSync(PAGE, page, "utf8");

const byStudio = new Map();
for (const p of published) {
  const k = studios[p.studio];
  byStudio.set(k, [...(byStudio.get(k) ?? []), p.name]);
}

console.log(`${published.length} projects rendered into index.html`);
for (const [studio, names] of byStudio)
  console.log(`  ${studio.padEnd(12)} ${names.length}  ${names.join(", ")}`);

const order = published.map((p) => p.slug).join(" -> ");
console.log(
  `\n  next-project loop (${published.length}): ${order} -> ${published[0].slug}`
);

const held = all.filter((p) => !p.published);
if (held.length)
  console.log(
    `\n  withheld (data retained, not rendered): ${held.map((p) => p.slug).join(", ")}`
  );
