/**
 * Generate the home work grid, /work/ and every /work/<slug>/ case study.
 *
 * Replaces make_projects.py, which carried its own hardcoded PROJECTS table.
 * projects.json is now the only place a project is defined; this script is the
 * only thing that writes project markup. Two consequences worth knowing:
 *
 *   - The home grid is rewritten between the PROJECTS markers in index.html.
 *     Everything else on that page is left alone.
 *   - Pages under work/ are written wholesale, and pages belonging to projects
 *     that are no longer published get deleted, so withdrawing a project can
 *     never strand a live URL.
 *
 * Projects with "published": false stay in projects.json but are excluded from
 * the grid, from /work/, from their own case-study page and from the
 * next-project loop.
 *
 *   node make_projects.mjs
 */
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { load, pairs, teaser } from "./layout.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));
const PAGE = join(ROOT, "index.html");
const WORK = join(ROOT, "work");

const START =
  "<!-- PROJECTS:START — generated by make_projects.mjs, do not edit by hand -->";
const END = "<!-- PROJECTS:END -->";

const die = (m) => {
  console.error(m);
  process.exit(1);
};

const esc = (s) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

// Studio metadata that isn't per-project. Mirrors what make_projects.py held.
const STUDIO_META = {
  byeveriart: { discipline: "Film", role: "Director of photography" },
  beframes: { discipline: "Photography", role: "Photographer" },
  everidesign: { discipline: "Identity", role: "Creative direction" },
};

const ARROW = `<svg viewBox="0 0 48 48" fill="none" focusable="false">
              <circle cx="24" cy="24" r="23.25" stroke="currentColor" stroke-width="1.5"/>
              <path d="M17.5 30.5 30.5 17.5M20 17.5h10.5V28" stroke="currentColor"
                    stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>`;

// ------------------------------------------------------------------ chrome
const head = (title, desc, theme = "#F8F8F8") => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<meta name="theme-color" content="${theme}">

<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/assets/favicon.svg">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet">

<link rel="stylesheet" href="/css/tokens.css">
<link rel="stylesheet" href="/css/base.css">
<link rel="stylesheet" href="/css/site.css">
</head>
<body>

<a class="sr-only" href="#main">Skip to content</a>
`;

const nav = (current = null) => {
  const mark = (href, label, key) =>
    `    <a class="nav__link" href="${href}"${
      key === current ? ' aria-current="page"' : ""
    }>${label}</a>`;
  return `
<nav class="nav" aria-label="Primary">
  <a class="nav__mark" href="/" aria-label="Everiart — home">
    <span class="nav__ring" aria-hidden="true"></span>
    <span class="nav__word">Everiart<span class="nav__dot">.</span></span>
  </a>

  <div class="nav__links">
${mark("/work/", "Work", "work")}
${mark("/#studios", "Studios", "studios")}
${mark("/#process", "Process", "process")}
${mark("/contact/", "Contact", "contact")}
  </div>
</nav>
`;
};

const FOOT = `
  <div class="wrap">
    <div class="foot">
      <span>&copy; 2026 EveriArt. All rights reserved.</span>
      <span>ByEveriArt &middot; EveriDesign &middot; BeFrames</span>
    </div>
  </div>
`;

const TAIL = `
<script type="module" src="/js/main.js"></script>
</body>
</html>
`;

// ------------------------------------------------------------------- tiles
function tile(studios, { project: p, size, delay }, indent, absolute) {
  const i = " ".repeat(indent);
  const src = absolute ? `/${p.thumb}` : p.thumb;
  return `${i}<a class="tile tile--${size} reveal" href="/work/${p.slug}/" data-delay="${delay}"
${i}   data-studio="${p.studio}" data-category="${esc(p.category)}" data-slug="${p.slug}">
${i}  <span class="tile__frame">
${i}    <img src="${src}" alt="${esc(`${p.name} — ${p.discipline.toLowerCase()}`)}" loading="lazy" decoding="async">
${i}    <span class="tile__arrow" aria-hidden="true">
${i}      ${ARROW}
${i}    </span>
${i}  </span>
${i}  <h3 class="tile__title">${esc(p.name)}</h3>
${i}  <p class="tile__studio">${studios[p.studio]}</p>
${i}</a>`;
}

function rows(studios, rowspec, indent, absolute) {
  const i = " ".repeat(indent);
  return rowspec
    .map((row) => {
      const cls = row.solo
        ? "pair pair--solo"
        : row.flip
          ? "pair pair--flip"
          : "pair";
      const inner = row.items
        .map((it) => tile(studios, it, indent + 2, absolute))
        .join("\n");
      return `${i}<div class="${cls}" data-studio="${row.items[0].project.studio}">\n${inner}\n${i}</div>`;
    })
    .join("\n\n");
}

// -------------------------------------------------------------- home grid
function buildHome(studios, rowspec) {
  let page = readFileSync(PAGE, "utf8");

  if (!page.includes(START) || !page.includes(END)) {
    // First run after taking over from make_projects.py: swap the hand-authored
    // tiles inside <div class="work"> for the markers, then fill them.
    const open = page.indexOf('<div class="work">');
    if (open < 0) die("index.html: no <div class=\"work\"> to generate into.");
    const from = page.indexOf(">", open) + 1;
    let depth = 1;
    let i = from;
    const re = /<div\b|<\/div>/g;
    re.lastIndex = from;
    let m;
    while ((m = re.exec(page))) {
      depth += m[0] === "</div>" ? -1 : 1;
      if (depth === 0) {
        i = m.index;
        break;
      }
    }
    if (depth !== 0) die("index.html: unbalanced <div class=\"work\">.");
    page = `${page.slice(0, from)}\n      ${START}\n      ${END}\n${page.slice(i)}`;
  }

  const block = `${START}\n\n${rows(studios, rowspec, 6, false)}\n\n      ${END}`;
  const a = page.indexOf(START);
  const b = page.indexOf(END) + END.length;
  writeFileSync(PAGE, page.slice(0, a) + block + page.slice(b), "utf8");
}

// --------------------------------------------------------------- /work/
function buildWorkIndex(studios, rowspec, n) {
  const html =
    head("Work — EveriArt", `${n} projects across three studios.`) +
    nav("work") +
    `
<main id="main" class="page">
  <div class="wrap">

    <header class="page__head">
      <h1 class="page__title">Work</h1>
      <p class="page__lede">
        ${n} projects across three studios — film, photography and identity.
      </p>
    </header>

    <div class="work">

${rows(studios, rowspec, 6, true)}

    </div>
  </div>
` +
    FOOT +
    `</main>
` +
    TAIL;

  mkdirSync(WORK, { recursive: true });
  writeFileSync(join(WORK, "index.html"), html, "utf8");
}

// ------------------------------------------------- /work/<slug>/ case study
function buildProject(studios, published, idx) {
  const p = published[idx];
  const next = published[(idx + 1) % published.length];
  const meta = STUDIO_META[p.studio];
  const label = studios[p.studio];

  // The gallery is the case study. Falling back to the thumb keeps a project
  // with no gallery yet from rendering an empty body.
  const figures = (p.gallery?.length ? p.gallery : [p.thumb])
    .map(
      (src, i) => `      <figure class="pfig reveal">
        <img src="/${src}" alt="${esc(p.name)} — image ${i + 1}" loading="lazy" decoding="async">
      </figure>`
    )
    .join("\n");

  const hero = p.hero ?? p.thumb;

  const html =
    head(
      `${p.name} — EveriArt`,
      `${p.name}: ${p.discipline.toLowerCase()} for ${label}.`,
      "#0B0B0C"
    ) +
    nav() +
    `
<main id="main" class="project">

  <header class="phero">
    <img class="phero__img" src="/${hero}" alt="" fetchpriority="high" decoding="async">
    <div class="phero__scrim" aria-hidden="true"></div>
    <div class="wrap phero__inner">
      <p class="phero__label">${label} &middot; ${meta.discipline}</p>
      <h1 class="phero__title">${esc(p.name)}</h1>
    </div>
  </header>

  <section class="section">
    <div class="wrap pmeta">
      <p class="pmeta__lede">${esc(p.lede ?? "")}</p>
      <dl class="pmeta__facts">
        <div class="pmeta__row"><dt>Client</dt><dd>${esc(p.name)}</dd></div>
        <div class="pmeta__row"><dt>Year</dt><dd>${p.year}</dd></div>
        <div class="pmeta__row"><dt>Category</dt><dd>${esc(p.category)}</dd></div>
        <div class="pmeta__row"><dt>Deliverables</dt><dd>${esc(p.discipline)}</dd></div>
        <div class="pmeta__row"><dt>Role</dt><dd>${meta.role}</dd></div>
      </dl>
    </div>
  </section>

  <section class="pbody">
    <div class="wrap">
${figures}
    </div>
  </section>

  <a class="next" href="/work/${next.slug}/">
    <span class="next__inner">
      <span class="next__word">Next project</span>
      <span class="next__arrow" aria-hidden="true">
        ${ARROW}
      </span>
    </span>
    <span class="next__meta">${esc(next.name)} &middot; ${studios[next.studio]}</span>
  </a>
` +
    FOOT +
    `</main>
` +
    TAIL;

  const dir = join(WORK, p.slug);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "index.html"), html, "utf8");
}

/** Remove case studies for projects that are no longer published. */
function prune(all, published) {
  const live = new Set(published.map((p) => p.slug));
  const dropped = [];
  for (const p of all) {
    if (live.has(p.slug)) continue;
    const dir = join(WORK, p.slug);
    if (existsSync(dir)) {
      rmSync(dir, { recursive: true, force: true });
      dropped.push(p.slug);
    }
  }
  return dropped;
}

// -------------------------------------------------------------------- main
const { studios, published, all } = load();
if (!published.length) die("projects.json: no published projects.");
for (const p of published)
  if (!studios[p.studio] || !STUDIO_META[p.studio])
    die(`${p.slug}: unknown studio "${p.studio}"`);

// The home page is a capped teaser (2 per studio + "See all work"); /work/
// carries the full catalogue. They are deliberately different row sets.
const teased = teaser(published);
const homeRows = pairs(teased);
const workRows = pairs(published);

buildHome(studios, homeRows);
buildWorkIndex(studios, workRows, published.length);
published.forEach((_, i) => buildProject(studios, published, i));
const dropped = prune(all, published);

console.log(`${published.length} published; ${teased.length} on the home teaser`);
for (const row of workRows) {
  const kind = row.solo ? "solo" : row.flip ? "pair (flipped)" : "pair";
  console.log(
    `  ${kind.padEnd(15)} ${row.items
      .map((it) => `${it.project.slug} [${it.size}]`)
      .join("  +  ")}`
  );
}
console.log(`\n  home grid   index.html`);
console.log(`  work index  work/index.html`);
console.log(`  case studies work/<slug>/index.html  x${published.length}`);

const loop = published.map((p) => p.slug).join(" -> ");
console.log(`\n  next-project loop: ${loop} -> ${published[0].slug}`);

if (dropped.length) console.log(`\n  pruned withheld pages: ${dropped.join(", ")}`);
const held = all.filter((p) => !p.published);
if (held.length)
  console.log(`  withheld (data retained): ${held.map((p) => p.slug).join(", ")}`);
