/**
 * Generate the home work grid, /work/ and every /work/<slug>/ case study.
 *
 * Replaces make_projects.py, which carried its own hardcoded PROJECTS table.
 * projects.json is now the only place a project is defined; this script is the
 * only thing that writes project markup. Two consequences worth knowing:
 *
 *   - The home grid is rewritten between the PROJECTS markers in index.html.
 *     Everything else on that page is left alone.
 *   - Pages under work/ are written wholesale, and pages belonging to projects
 *     that are no longer published get deleted, so withdrawing a project can
 *     never strand a live URL.
 *
 * Projects with "published": false stay in projects.json but are excluded from
 * the grid, from /work/, from their own case-study page and from the
 * next-project loop.
 *
 *   node make_projects.mjs
 */
import {
  existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { load, pairs, teaser } from "./layout.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));
const PAGE = join(ROOT, "index.html");
const WORK = join(ROOT, "work");

const START =
  "<!-- PROJECTS:START — generated by make_projects.mjs, do not edit by hand -->";
const END = "<!-- PROJECTS:END -->";

const die = (m) => {
  console.error(m);
  process.exit(1);
};

const esc = (s) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

// Studio metadata that isn't per-project. Mirrors what make_projects.py held.
const STUDIO_META = {
  byeveriart: { discipline: "Film", role: "Director of photography" },
  beframes: { discipline: "Photography", role: "Photographer" },
  everidesign: { discipline: "Identity", role: "Creative direction" },
};

const ARROW = `<svg viewBox="0 0 48 48" fill="none" focusable="false">
              <circle cx="24" cy="24" r="23.25" stroke="currentColor" stroke-width="1.5"/>
              <path d="M17.5 30.5 30.5 17.5M20 17.5h10.5V28" stroke="currentColor"
                    stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>`;

// ------------------------------------------------------------------ chrome
const head = (title, desc, theme = "#0D132D") => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<meta name="theme-color" content="${theme}">

<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/assets/favicon.svg">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet">

<link rel="stylesheet" href="/css/tokens.css">
<link rel="stylesheet" href="/css/base.css">
<link rel="stylesheet" href="/css/site.css">
</head>
<body>

<a class="sr-only" href="#main">Skip to content</a>
`;

const nav = (current = null) => {
  const mark = (href, label, key) =>
    `    <a class="nav__link" href="${href}"${
      key === current ? ' aria-current="page"' : ""
    }>${label}</a>`;
  return `
<nav class="nav" aria-label="Primary">
  <a class="nav__mark" href="/" aria-label="Everiart — home">
    <span class="nav__ring" aria-hidden="true"></span>
    <span class="nav__word">Everiart<span class="nav__dot">.</span></span>
  </a>

  <div class="nav__links">
${mark("/work/", "Work", "work")}
${mark("/#studios", "Studios", "studios")}
${mark("/#process", "Process", "process")}
${mark("/contact/", "Contact", "contact")}
  </div>
</nav>
`;
};

const FOOT = `
  <div class="wrap">
    <div class="foot">
      <span>&copy; 2026 EveriArt. All rights reserved.</span>
      <span>ByEveriArt &middot; EveriDesign &middot; BeFrames</span>
    </div>
  </div>
`;

const TAIL = `
<script type="module" src="/js/main.js"></script>
</body>
</html>
`;

/**
 * The ambient zoom's phase, per tile.
 *
 * Derived from the slug rather than from Math.random or the array index: the
 * value has to be stable across builds (a random one would dirty every page
 * on every run) and it has to survive reordering projects.json. All that
 * actually matters is that no two tiles are in step — tiles drifting in
 * lockstep read as one moving background, which is the opposite of the point.
 */
function kenPhase(slug) {
  const h = [...slug].reduce((a, c) => (a * 31 + c.charCodeAt(0)) >>> 0, 7);
  const dur = 30 + (h % 13);                          // 30–42s per sweep
  return {
    dur,
    delay: -((h >>> 5) % 100) / 100 * dur,           // start anywhere in it
    dir: (h >>> 3) % 2 ? "alternate-reverse" : "alternate",
  };
}

// ------------------------------------------------------------------- tiles
function tile(studios, { project: p, size, delay }, indent, absolute) {
  const i = " ".repeat(indent);
  const src = absolute ? `/${p.thumb}` : p.thumb;
  // data-reel is what js/video.js keys off. Absent for projects with no
  // reel, so those tiles keep the still and never build a <video>.
  const reel = p.reel ? ` data-reel="${esc(p.reel)}"` : "";
  const k = kenPhase(p.slug);
  // .tile__zoom carries the ambient motion, and js/video.js appends the hover
  // reel INTO it rather than beside it. One animated element, so the still and
  // the video are framed identically at every instant of the cross-fade — two
  // separately animated elements would drift apart and pop mid-fade — and one
  // compositor layer per tile instead of two. The arrow stays outside it, so
  // it is not dragged around by the pan.
  return `${i}<a class="tile tile--${size} reveal" href="/work/${p.slug}/" data-delay="${delay}"
${i}   data-studio="${p.studio}" data-category="${esc(p.category)}" data-slug="${p.slug}"${reel}>
${i}  <span class="tile__frame">
${i}    <span class="tile__zoom" style="--ken-dur:${k.dur}s;--ken-delay:${k.delay.toFixed(2)}s;--ken-dir:${k.dir}">
${i}      <img src="${src}" alt="${esc(`${p.name} — ${p.discipline.toLowerCase()}`)}" loading="lazy" decoding="async">
${i}    </span>
${i}    <span class="tile__arrow" aria-hidden="true">
${i}      ${ARROW}
${i}    </span>
${i}  </span>
${i}  <h3 class="tile__title">${esc(p.name)}</h3>
${i}  <p class="tile__studio">${studios[p.studio]}</p>
${i}</a>`;
}

function rows(studios, rowspec, indent, absolute) {
  const i = " ".repeat(indent);
  return rowspec
    .map((row) => {
      const cls = row.solo
        ? "pair pair--solo"
        : row.flip
          ? "pair pair--flip"
          : "pair";
      const inner = row.items
        .map((it) => tile(studios, it, indent + 2, absolute))
        .join("\n");
      return `${i}<div class="${cls}" data-studio="${row.items[0].project.studio}">\n${inner}\n${i}</div>`;
    })
    .join("\n\n");
}

// -------------------------------------------------------------- home grid
function buildHome(studios, rowspec) {
  let page = readFileSync(PAGE, "utf8");

  if (!page.includes(START) || !page.includes(END)) {
    // First run after taking over from make_projects.py: swap the hand-authored
    // tiles inside <div class="work"> for the markers, then fill them.
    const open = page.indexOf('<div class="work">');
    if (open < 0) die("index.html: no <div class=\"work\"> to generate into.");
    const from = page.indexOf(">", open) + 1;
    let depth = 1;
    let i = from;
    const re = /<div\b|<\/div>/g;
    re.lastIndex = from;
    let m;
    while ((m = re.exec(page))) {
      depth += m[0] === "</div>" ? -1 : 1;
      if (depth === 0) {
        i = m.index;
        break;
      }
    }
    if (depth !== 0) die("index.html: unbalanced <div class=\"work\">.");
    page = `${page.slice(0, from)}\n      ${START}\n      ${END}\n${page.slice(i)}`;
  }

  const block = `${START}\n\n${rows(studios, rowspec, 6, false)}\n\n      ${END}`;
  const a = page.indexOf(START);
  const b = page.indexOf(END) + END.length;
  writeFileSync(PAGE, page.slice(0, a) + block + page.slice(b), "utf8");
}

// ---------------------------------------------------------- /work/ index
/**
 * /work/ is the full published catalogue on the same asymmetric grid the home
 * page uses — one smaller tile beside one larger, alternating which side
 * carries the weight, full-bleed, no card chrome.
 *
 * It replaces the sequential lookbook, which is gone. The home page and /work/
 * now differ only in how much they show: home is a capped teaser (2 per studio
 * + "See all work"), /work/ is everything. Same tile(), same rows(), same
 * pairing rules out of layout.mjs, so a change to the tile is a change to both
 * and cannot drift between them.
 *
 * Nothing is sized to the current project count. Rows come from pairs() over
 * the whole published array; six or sixty behave identically, and a studio
 * with an odd count closes on a solo full-width tile rather than borrowing a
 * partner from the next studio.
 *
 * The filter is the home page's control, unchanged. It is worth more here than
 * there: this is the page that carries everything, so it is the page where
 * narrowing to one discipline is actually a useful thing to do. Pairs are
 * studio-pure, so it hides whole rows and can never orphan half of one.
 */
function buildWorkIndex(studios, published) {
  const n = published.length;
  const rowspec = pairs(published);

  const html =
    head("Work — EveriArt", `${n} projects across three studios.`) +
    nav("work") +
    `
<main id="main" class="page on-dark">
  <div class="wrap">

    <header class="page__head">
      <h1 class="page__title">Work.</h1>
      <p class="page__lede">
        Every published project across the three studios. Filter by
        discipline, or see everything at once.
      </p>
    </header>

    <div class="filter" role="tablist" aria-label="Filter work by studio">
      <span class="filter__rule" aria-hidden="true"></span>
      <button class="filter__btn" role="tab" aria-selected="true"  data-filter="all">All</button>
      <button class="filter__btn" role="tab" aria-selected="false" data-filter="byeveriart">Film</button>
      <button class="filter__btn" role="tab" aria-selected="false" data-filter="everidesign">Identity</button>
      <button class="filter__btn" role="tab" aria-selected="false" data-filter="beframes">Photography</button>
    </div>

    <div class="work">
${rows(studios, rowspec, 6, true)}
    </div>

  </div>
` +
    FOOT +
    `</main>
` +
    TAIL;

  mkdirSync(WORK, { recursive: true });
  writeFileSync(join(WORK, "index.html"), html, "utf8");
  return rowspec;
}

// ------------------------------------------------- /work/<slug>/ case study
function buildProject(studios, published, idx) {
  const p = published[idx];
  const next = published[(idx + 1) % published.length];
  const meta = STUDIO_META[p.studio];
  const label = studios[p.studio];

  // The gallery is the case study. Falling back to the thumb keeps a project
  // with no gallery yet from rendering an empty body.
  const figures = (p.gallery?.length ? p.gallery : [p.thumb])
    .map(
      (src, i) => `      <figure class="pfig reveal">
        <img src="/${src}" alt="${esc(p.name)} — image ${i + 1}" loading="lazy" decoding="async">
      </figure>`
    )
    .join("\n");

  const hero = p.hero ?? p.thumb;

  const html =
    head(
      `${p.name} — EveriArt`,
      `${p.name}: ${p.discipline.toLowerCase()} for ${label}.`,
      "#0B0B0C"
    ) +
    nav() +
    `
<main id="main" class="project">

  <header class="phero">
    <img class="phero__img" src="/${hero}" alt="" fetchpriority="high" decoding="async">
    <div class="phero__scrim" aria-hidden="true"></div>
    <div class="wrap phero__inner">
      <p class="phero__label">${label} &middot; ${meta.discipline}</p>
      <h1 class="phero__title">${esc(p.name)}</h1>
    </div>
  </header>

  <section class="section">
    <div class="wrap pmeta">
      <p class="pmeta__lede">${esc(p.lede ?? "")}</p>
      <dl class="pmeta__facts">
        <div class="pmeta__row"><dt>Client</dt><dd>${esc(p.name)}</dd></div>
        <div class="pmeta__row"><dt>Year</dt><dd>${p.year}</dd></div>
        <div class="pmeta__row"><dt>Category</dt><dd>${esc(p.category)}</dd></div>
        <div class="pmeta__row"><dt>Deliverables</dt><dd>${esc(p.discipline)}</dd></div>
        <div class="pmeta__row"><dt>Role</dt><dd>${meta.role}</dd></div>
      </dl>
    </div>
  </section>

  <section class="pbody">
    <div class="wrap">
${figures}
    </div>
  </section>

  <a class="next" href="/work/${next.slug}/">
    <span class="next__inner">
      <span class="next__word">Next project</span>
      <span class="next__arrow" aria-hidden="true">
        ${ARROW}
      </span>
    </span>
    <span class="next__meta">${esc(next.name)} &middot; ${studios[next.studio]}</span>
  </a>
` +
    FOOT +
    `</main>
` +
    TAIL;

  const dir = join(WORK, p.slug);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "index.html"), html, "utf8");
}

/**
 * Remove every case-study directory that no longer belongs to a published
 * project.
 *
 * This scans work/ rather than walking projects.json, because the two ways a
 * page goes stale are different: a project can be flipped to published:false,
 * or its entry can be deleted outright. Only the directory listing catches
 * both, and an orphaned /work/<slug>/ is a live URL serving a project the site
 * no longer claims to have.
 */
function prune(published) {
  const live = new Set(published.map((p) => p.slug));
  if (!existsSync(WORK)) return [];
  const dropped = [];
  for (const entry of readdirSync(WORK, { withFileTypes: true })) {
    if (!entry.isDirectory() || live.has(entry.name)) continue;
    rmSync(join(WORK, entry.name), { recursive: true, force: true });
    dropped.push(entry.name);
  }
  return dropped;
}

// -------------------------------------------------------------------- main
const { studios, published, all } = load();
if (!published.length) die("projects.json: no published projects.");
for (const p of published)
  if (!studios[p.studio] || !STUDIO_META[p.studio])
    die(`${p.slug}: unknown studio "${p.studio}"`);

// Both surfaces are the same asymmetric grid; they differ only in how much
// they show. The home page is a capped teaser (2 per studio + "See all
// work"), /work/ is the whole published catalogue.
const teased = teaser(published);
const homeRows = pairs(teased);

buildHome(studios, homeRows);
const workRows = buildWorkIndex(studios, published);
published.forEach((_, i) => buildProject(studios, published, i));
const dropped = prune(published);

console.log(`${published.length} published; ${teased.length} on the home teaser`);
for (const row of homeRows) {
  const kind = row.solo ? "solo" : row.flip ? "pair (flipped)" : "pair";
  console.log(
    `  ${kind.padEnd(15)} ${row.items
      .map((it) => `${it.project.slug} [${it.size}]`)
      .join("  +  ")}`
  );
}
console.log(`\n  ${workRows.length} rows on /work/`);
for (const row of workRows) {
  const kind = row.solo ? "solo" : row.flip ? "pair (flipped)" : "pair";
  console.log(
    `  ${kind.padEnd(15)} ${row.items
      .map((it) => `${it.project.slug} [${it.size}]`)
      .join("  +  ")}`
  );
}

console.log(`\n  home grid    index.html`);
console.log(`  work grid    work/index.html`);
console.log(`  case studies work/<slug>/index.html  x${published.length}`);

const loop = published.map((p) => p.slug).join(" -> ");
console.log(`\n  next-project loop: ${loop} -> ${published[0].slug}`);

if (dropped.length) console.log(`\n  pruned stale case studies: ${dropped.join(", ")}`);
const held = all.filter((p) => !p.published);
if (held.length)
  console.log(`  withheld (data retained): ${held.map((p) => p.slug).join(", ")}`);
